# Generated by Django 4.1.4 on 2023-01-13 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('DiseaseID', models.AutoField(primary_key=True, serialize=False)),
                ('DiseaseName', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('DoctorID', models.AutoField(primary_key=True, serialize=False)),
                ('DoctorName', models.CharField(max_length=500)),
                ('DoctorAddress', models.CharField(max_length=500)),
                ('Department', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('MedicineID', models.AutoField(primary_key=True, serialize=False)),
                ('MedicineName', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('PatientID', models.AutoField(primary_key=True, serialize=False)),
                ('PatientName', models.CharField(max_length=500)),
                ('PatientAddress', models.CharField(max_length=500)),
                ('DiseaseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='H1.diseases')),
            ],
        ),
    ]
