# Generated by Django 4.1.4 on 2023-01-13 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0002_rename_diseaseid_patients_disease'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='Disease',
            new_name='Diseases',
        ),
    ]
