# Generated by Django 4.1.4 on 2023-01-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0003_rename_disease_patients_diseases'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuMaster',
            fields=[
                ('MenuID', models.AutoField(primary_key=True, serialize=False)),
                ('MenuName', models.CharField(max_length=200)),
            ],
        ),
    ]
