# Generated by Django 4.1.4 on 2023-01-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0004_menumaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumaster',
            name='MenuLink',
            field=models.CharField(default='link', max_length=200),
        ),
        migrations.AddField(
            model_name='menumaster',
            name='MenuOrder',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menumaster',
            name='ParentMenu',
            field=models.IntegerField(default=0),
        ),
    ]
