# Generated by Django 4.1.4 on 2023-01-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0005_menumaster_menulink_menumaster_menuorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='DiseaseName',
            field=models.CharField(max_length=500),
        ),
    ]
