# Generated by Django 4.1.4 on 2023-01-16 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0006_alter_diseases_diseasename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepartmentID', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('StateID', models.AutoField(primary_key=True, serialize=False)),
                ('StateName', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='patients',
            name='PatientName',
        ),
        migrations.AddField(
            model_name='patients',
            name='DOB',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patients',
            name='FirstName',
            field=models.CharField(default='NONE', max_length=500),
        ),
        migrations.AddField(
            model_name='patients',
            name='Gender',
            field=models.CharField(default='NONE', max_length=500),
        ),
        migrations.AddField(
            model_name='patients',
            name='LastName',
            field=models.CharField(default='NONE', max_length=500),
        ),
    ]
