# Generated by Django 4.1.4 on 2023-01-17 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0008_gender_roomtypeid_specialization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomTypeID',
            new_name='RoomType',
        ),
    ]
