# Generated by Django 4.1.4 on 2023-01-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0009_rename_roomtypeid_roomtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='DoctorName',
        ),
        migrations.AddField(
            model_name='doctors',
            name='FirstName',
            field=models.CharField(default='NONE', max_length=500),
        ),
        migrations.AddField(
            model_name='doctors',
            name='LastName',
            field=models.CharField(default='NONE', max_length=500),
        ),
        migrations.AddField(
            model_name='doctors',
            name='MiddleName',
            field=models.CharField(default='NONE', max_length=500),
        ),
        migrations.AddField(
            model_name='patients',
            name='MiddleName',
            field=models.CharField(default='NONE', max_length=500),
        ),
        migrations.AddField(
            model_name='patients',
            name='Mobile',
            field=models.CharField(default=1111111111, max_length=10),
        ),
    ]
