# Generated by Django 4.1.4 on 2023-01-17 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0010_remove_doctors_doctorname_doctors_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='Gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='H1.gender'),
        ),
    ]
