# Generated by Django 4.1.4 on 2023-01-17 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0011_alter_patients_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='Diseases',
        ),
    ]
