# Generated by Django 4.1.4 on 2023-01-17 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0012_remove_patients_diseases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='DOB',
            field=models.DateField(default=datetime.datetime(2023, 1, 17, 13, 37, 45, 755599)),
        ),
    ]
