# Generated by Django 4.1.4 on 2023-01-17 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0015_doctors_gender_doctors_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='Gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='H1.gender'),
        ),
    ]
