# Generated by Django 4.1.4 on 2023-01-17 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0016_alter_doctors_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='Specialization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='H1.specialization'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='Department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='H1.department'),
        ),
    ]
