# Generated by Django 4.1.4 on 2023-01-21 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0017_doctors_specialization_alter_doctors_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('TimeID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Time', models.TimeField(default=datetime.time)),
            ],
        ),
    ]
