# Generated by Django 4.1.4 on 2023-01-22 12:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0018_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('StatusID', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(default='open', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('AppointmentID', models.AutoField(primary_key=True, serialize=False)),
                ('AppointmentDate', models.DateField(default=django.utils.timezone.now)),
                ('Problem', models.CharField(max_length=5000)),
                ('Status', models.CharField(default='Active', max_length=50)),
                ('Prescription', models.CharField(default='None', max_length=5000)),
                ('Report', models.CharField(default='None', max_length=5000)),
                ('Department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='H1.department')),
                ('Doctor', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='H1.doctors')),
                ('Patient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='H1.patients')),
                ('Time', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='H1.time')),
            ],
        ),
    ]
