# Generated by Django 4.1.4 on 2023-01-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0019_status_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='PatientImage',
            field=models.ImageField(default='', upload_to='patient'),
        ),
    ]
