# Generated by Django 4.1.4 on 2023-01-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0020_patients_patientimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='DoctorImage',
            field=models.ImageField(default='', upload_to='doctor'),
        ),
    ]
