# Generated by Django 4.1.4 on 2023-01-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0021_doctors_doctorimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='DoctorImage',
            field=models.ImageField(default='', upload_to='doctor/'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='PatientImage',
            field=models.ImageField(default='', upload_to='patient/'),
        ),
    ]
