# Generated by Django 4.1.4 on 2023-01-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0022_alter_doctors_doctorimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='DoctorImage',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='patients',
            name='PatientImage',
            field=models.CharField(default='', max_length=255),
        ),
    ]
