# Generated by Django 4.1.4 on 2023-01-25 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0023_alter_doctors_doctorimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='H1.department'),
        ),
    ]
