# Generated by Django 4.1.4 on 2023-01-25 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0024_alter_appointment_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Doctor',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='H1.doctors'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='H1.patients'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='H1.time'),
        ),
    ]
