# Generated by Django 4.1.4 on 2023-01-25 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0025_alter_appointment_doctor_alter_appointment_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='deletedpatientapp',
            fields=[
                ('AppointmentID', models.AutoField(primary_key=True, serialize=False)),
                ('Patient', models.CharField(max_length=250)),
                ('Department', models.CharField(max_length=250)),
                ('Doctor', models.CharField(max_length=250)),
                ('Time', models.TimeField()),
                ('AppointmentDate', models.DateField()),
                ('Problem', models.CharField(max_length=3000)),
                ('Status', models.CharField(max_length=50)),
                ('Prescription', models.CharField(max_length=4000)),
                ('Report', models.CharField(max_length=3000)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='H1.department'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Doctor',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='H1.doctors'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='H1.patients'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='H1.time'),
        ),
    ]
