# Generated by Django 4.1.4 on 2023-01-25 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0026_deletedpatientapp_alter_appointment_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletedpatientapp',
            name='Patient',
        ),
        migrations.AddField(
            model_name='deletedpatientapp',
            name='Doctor_L',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AddField(
            model_name='deletedpatientapp',
            name='Doctor_M',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AddField(
            model_name='deletedpatientapp',
            name='Doctor_Mo',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AddField(
            model_name='deletedpatientapp',
            name='Patient_F',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AddField(
            model_name='deletedpatientapp',
            name='Patient_L',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AddField(
            model_name='deletedpatientapp',
            name='Patient_M',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AddField(
            model_name='deletedpatientapp',
            name='Patient_Mo',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Department',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='H1.department'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Doctor',
            field=models.ForeignKey(default=4, null=True, on_delete=django.db.models.deletion.SET_NULL, to='H1.doctors'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Patient',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='H1.patients'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Time',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='H1.time'),
        ),
        migrations.AlterField(
            model_name='deletedpatientapp',
            name='Department',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='deletedpatientapp',
            name='Doctor',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
