# Generated by Django 4.1.4 on 2023-01-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0027_remove_deletedpatientapp_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedpatientapp',
            name='PatientImage',
            field=models.CharField(default='/patient/no-photo.jpg', max_length=3000),
        ),
    ]
