# Generated by Django 4.1.4 on 2023-01-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0028_deletedpatientapp_patientimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deletedpatientapp',
            old_name='Doctor',
            new_name='Doctor_F',
        ),
    ]
