# Generated by Django 4.1.4 on 2023-01-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0030_alter_appointment_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandleLogin',
            fields=[
                ('LoginID', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=50)),
                ('UserPassword', models.CharField(max_length=50)),
            ],
        ),
    ]
