# Generated by Django 4.1.4 on 2023-01-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0031_handlelogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlelogin',
            name='superuser',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
