# Generated by Django 4.1.4 on 2023-01-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0032_handlelogin_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumaster',
            name='HasSubmenu',
            field=models.IntegerField(default=1),
        ),
    ]
