# Generated by Django 4.1.4 on 2023-01-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0033_menumaster_hassubmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('HospitalID', models.AutoField(primary_key=True, serialize=False)),
                ('HospitalName', models.CharField(max_length=100)),
                ('HospitalAddress', models.CharField(max_length=1000)),
                ('HospitalMobile', models.CharField(max_length=10)),
                ('HospitalLandline', models.CharField(max_length=10)),
                ('HospitalLogo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='handlelogin',
            name='superuser',
            field=models.IntegerField(default=0),
        ),
    ]
