# Generated by Django 4.1.4 on 2023-01-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0034_hospital_alter_handlelogin_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='HospitalLandline',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='HospitalMobile',
            field=models.CharField(max_length=50),
        ),
    ]
