# Generated by Django 4.1.4 on 2023-01-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0035_alter_hospital_hospitallandline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='Email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
    ]
