# Generated by Django 4.1.4 on 2023-02-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0036_patients_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='Consent',
            field=models.IntegerField(default=0),
        ),
    ]
