# Generated by Django 4.1.4 on 2023-02-05 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0037_patients_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='ApprovalDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
